version: '3'
services:
  postgres:
    image: postgres:11.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: domain-checker
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always

  checker:
    container_name: checker
    build: ./google-domain-checker
    restart: always
    volumes:
      - ./google-domain-checker:/go/src/app
    ports:
      - 8084:8084
    depends_on:
      - postgres
      - rabbit
    environment:
      WAIT_HOSTS: postgres:5432, rabbit:5672

  notifier:
    container_name: notifier
    build: ./notifier
    restart: always
    depends_on:
      - rabbit
    volumes:
      - ./notifier:/go/src/app
    ports:
      - 8085:8085
    environment:
      WAIT_HOSTS: rabbit:5672

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 15672:15672
      - 5672:5672

